spring:
  datasource:
    url: ${SPRING_SANDBOX_DATASOURCE_URL}
    username: ${SPRING_SANDBOX_DATASOURCE_USERNAME}
    password: ${SPRING_SANDBOX_DATASOURCE_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations:
    - classpath*:/static/mybatis/com/example/springsandbox/mapper/*.xml
    - classpath*:/static/mybatis/com/example/springsandbox/mapper/custom/*.xml
  configuration:
    map-underscore-to-camel-case: true
